// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "CHANGELOG",
        "revision": "8a872fe193a26678351bfcd30ce762bf"
    },
    {
        "url": "Copy of index.html.txt",
        "revision": "c594d507f66dc45d705f8c51d130ef89"
    },
    {
        "url": "index.html",
        "revision": "9c9b2c8908545300e8b080fbe1b29d88"
    },
    {
        "url": "index.php",
        "revision": "bef9a7d66cff9c50359d1e6e4b5d8921"
    },
    {
        "url": "INSTALL",
        "revision": "4b8cd3c0df34ccdf9eda43633db9ef2a"
    },
    {
        "url": "LICENSE",
        "revision": "01a2438b1b13b50bedf2778fc1678265"
    },
    {
        "url": "manifest.json",
        "revision": "08499ada2484b62e678efdbb5eb03091"
    },
    {
        "url": "offline.html",
        "revision": "8987c4b748db7cbdf5e4c6165507121b"
    },
    {
        "url": "phpqrcode.php",
        "revision": "5d6fa18048ed122bc94aec4f88b173d0"
    },
    {
        "url": "qrbitstream.php",
        "revision": "7b95645db7e06aba3b55af7dd249663b"
    },
    {
        "url": "qrcode.min.js",
        "revision": "517b55d3688ce9ef1085a3d9632bcb97"
    },
    {
        "url": "qrconfig.php",
        "revision": "15c58fed3d55a98cda8abeed8c336fa6"
    },
    {
        "url": "qrconst.php",
        "revision": "4cd7d63ff0b638020e6b0c6d11133d09"
    },
    {
        "url": "qrencode.php",
        "revision": "dda263c8a9742aaa71cc302820308541"
    },
    {
        "url": "qrimage.php",
        "revision": "2d1588686abe320c3bf003c94e967ce0"
    },
    {
        "url": "qrinput.php",
        "revision": "07ee5315fb6c319dc208de59a9de95c0"
    },
    {
        "url": "qrlib.php",
        "revision": "4d2b63e34326b0df5153be6d928ec960"
    },
    {
        "url": "qrmask.php",
        "revision": "12ce875d67e242532e2b0da9f0a334ee"
    },
    {
        "url": "qrrscode.php",
        "revision": "17af6b8769e70c132f227b089152a47f"
    },
    {
        "url": "qrspec.php",
        "revision": "7d276c5a768c04d62ae0afde8abaad2d"
    },
    {
        "url": "qrsplit.php",
        "revision": "206c8468e0089be5f58453cbbd003ec0"
    },
    {
        "url": "qrtools.php",
        "revision": "27aea0ee5d1395d80ef4b9ce7d08fa40"
    },
    {
        "url": "README",
        "revision": "f541b0b72589a7d3383eface763af72b"
    },
    {
        "url": "readme file for index.pdf",
        "revision": "1dbcb867741c91b4f2852491cd538bad"
    },
    {
        "url": "readme file for index.php.docx",
        "revision": "e5b10a2cd13f4ca4c21383cc364ead19"
    },
    {
        "url": "receipt-44221979.png",
        "revision": "87a8e4a6f7123dcf4ecc624d682dc571"
    },
    {
        "url": "receipt-44361536.png",
        "revision": "9433aed68cbbcf8be34e3297afc1b6b2"
    },
    {
        "url": "receipt-44819471.png",
        "revision": "55ba061702ca1d18d004d0c7e7a0b484"
    },
    {
        "url": "receipt-44910508.png",
        "revision": "b0f28da7e0696027cab37d6c9ce2c4f6"
    },
    {
        "url": "receipt-46424879.png",
        "revision": "16a361277cd0b76788205aac8a239383"
    },
    {
        "url": "receipt-receipt-1755253154847.png",
        "revision": "fb0c52666b1a6b86635c7e785501cb3f"
    },
    {
        "url": "receipt-receipt-17552531548472.png",
        "revision": "2be0687725f1e654178dfc1a1d691f1a"
    },
    {
        "url": "sw.js",
        "revision": "43fc71595816eab513a1be4a4d961f4a"
    },
    {
        "url": "VERSION",
        "revision": "1be049d58921c68c0ce38169a785ac20"
    },
    {
        "url": "bindings/tcpdf/qrcode.php",
        "revision": "c0a11c1419131032614c0c5d2c9eb145"
    },
    {
        "url": "cache/frame_1.dat",
        "revision": "9966a137ae5c422c423c64664a6e7525"
    },
    {
        "url": "cache/frame_1.png",
        "revision": "411b1640bd31fb729f2133abcd06147c"
    },
    {
        "url": "cache/frame_10.dat",
        "revision": "5322d931be649e5ccec61461d67dd321"
    },
    {
        "url": "cache/frame_10.png",
        "revision": "94e6c5ecb12f212f27dcff20e82a795b"
    },
    {
        "url": "cache/frame_11.dat",
        "revision": "79e3ee85484b12fcc4fdc1907510dd90"
    },
    {
        "url": "cache/frame_11.png",
        "revision": "f6ef45cec274ec241a873ef22df7f45e"
    },
    {
        "url": "cache/frame_12.dat",
        "revision": "37ccf648fe2fc810ec81fa0f8c3820f1"
    },
    {
        "url": "cache/frame_12.png",
        "revision": "76152b897afbf40707bf238b5c6dd172"
    },
    {
        "url": "cache/frame_13.dat",
        "revision": "b04711a3b19ec79c84549843c5557ac9"
    },
    {
        "url": "cache/frame_13.png",
        "revision": "d6ed6af6d34cf2e8a8d24ae08400fae4"
    },
    {
        "url": "cache/frame_14.dat",
        "revision": "250770c3d53b29c438f8c0882e1d56d0"
    },
    {
        "url": "cache/frame_14.png",
        "revision": "d681e5d008e03ef3b2a174da3b77067a"
    },
    {
        "url": "cache/frame_15.dat",
        "revision": "8e37257a86d3bb454dc2568d94673f6c"
    },
    {
        "url": "cache/frame_15.png",
        "revision": "ef5b3f6e8fc23ebc14a8929a5300da95"
    },
    {
        "url": "cache/frame_16.dat",
        "revision": "7032d38df7b8225e306c6940b9380e2b"
    },
    {
        "url": "cache/frame_16.png",
        "revision": "3e55f66956d8035aa8d3bc1e7fc160f7"
    },
    {
        "url": "cache/frame_17.dat",
        "revision": "f492c83b8c1c940ee37f41407d0a6c23"
    },
    {
        "url": "cache/frame_17.png",
        "revision": "03db7f215625032749e912f2aab2a701"
    },
    {
        "url": "cache/frame_18.dat",
        "revision": "0780fa437cde6b605d86ba1a2234f19e"
    },
    {
        "url": "cache/frame_18.png",
        "revision": "b52277f3cd98a8f46663f5091b0a9681"
    },
    {
        "url": "cache/frame_19.dat",
        "revision": "dd0bf43626ee9dc7694382311d94df7f"
    },
    {
        "url": "cache/frame_19.png",
        "revision": "aaa7c06298eac23c24c41372b13e99ad"
    },
    {
        "url": "cache/frame_2.dat",
        "revision": "d2063daff8eada7d4a22cedae30f5d04"
    },
    {
        "url": "cache/frame_2.png",
        "revision": "1ae37415f42c6dbfed330acee0e488d6"
    },
    {
        "url": "cache/frame_20.dat",
        "revision": "a3a1eb820b13832a3cfceb8af8fb2ee5"
    },
    {
        "url": "cache/frame_20.png",
        "revision": "a674ebc38712054a376b181db975e02b"
    },
    {
        "url": "cache/frame_21.dat",
        "revision": "f35be2f92c1f6546b5896916e76c9b34"
    },
    {
        "url": "cache/frame_21.png",
        "revision": "e29a7e7e2516dfec6cf283c12e83224b"
    },
    {
        "url": "cache/frame_22.dat",
        "revision": "080bb29f0d4fb1c04f2973ef87b91f5a"
    },
    {
        "url": "cache/frame_22.png",
        "revision": "4faa3626cb02b8c824247b7f8cec0ee1"
    },
    {
        "url": "cache/frame_23.dat",
        "revision": "009203ec77f7fd1e19b495c3f1b08a44"
    },
    {
        "url": "cache/frame_23.png",
        "revision": "3c9cc974afe24e8d7750c72d3bbc298f"
    },
    {
        "url": "cache/frame_24.dat",
        "revision": "c1b69627f5e2705025d7db7b523e4892"
    },
    {
        "url": "cache/frame_24.png",
        "revision": "6722efb1632fc9a23f687d67060514cd"
    },
    {
        "url": "cache/frame_25.dat",
        "revision": "85f80a8a72dd8ecfe50b73dd04c03428"
    },
    {
        "url": "cache/frame_25.png",
        "revision": "d33e136b0ef7cbdd31857d395219efa1"
    },
    {
        "url": "cache/frame_26.dat",
        "revision": "00a2327c48e4e8019e4f1bf1173ea6a7"
    },
    {
        "url": "cache/frame_26.png",
        "revision": "bfba16b8705888625f6a1efa26008f8e"
    },
    {
        "url": "cache/frame_27.dat",
        "revision": "f74a3e9017abb34cf10d9161db6944a6"
    },
    {
        "url": "cache/frame_27.png",
        "revision": "4201dc61a80d2cdbc5180abdbf3cb09f"
    },
    {
        "url": "cache/frame_28.dat",
        "revision": "76acbf4f5b5214113a329585a43e4c88"
    },
    {
        "url": "cache/frame_28.png",
        "revision": "ba1fa3b05d4e0ce79711857b845a0d8a"
    },
    {
        "url": "cache/frame_29.dat",
        "revision": "8571093499a6bdb0ecb179f4ba2420ea"
    },
    {
        "url": "cache/frame_29.png",
        "revision": "2adea50109f78d7341993b2195a715c3"
    },
    {
        "url": "cache/frame_3.dat",
        "revision": "2699cfca6a5e65aacd0c7fbb6c9084d1"
    },
    {
        "url": "cache/frame_3.png",
        "revision": "2aed9e9c0e87bbee7443546ba55c3cf6"
    },
    {
        "url": "cache/frame_30.dat",
        "revision": "255e0419353a95fd6ed075683ebee392"
    },
    {
        "url": "cache/frame_30.png",
        "revision": "ed732e8b8a612389b31544b8b6a460b5"
    },
    {
        "url": "cache/frame_31.dat",
        "revision": "69e65a7e068f7743b31a33f1faad9bac"
    },
    {
        "url": "cache/frame_31.png",
        "revision": "6642919250856e737f3fdf2db8073178"
    },
    {
        "url": "cache/frame_32.dat",
        "revision": "eba1b97fa1d0a8b28d2374323848534d"
    },
    {
        "url": "cache/frame_32.png",
        "revision": "51231a4d0f1d7520c3faf374b95153f0"
    },
    {
        "url": "cache/frame_33.dat",
        "revision": "166082e4520386ae368ece323cb96e16"
    },
    {
        "url": "cache/frame_33.png",
        "revision": "c281e359d10cfca77e6c9d24bbacb86f"
    },
    {
        "url": "cache/frame_34.dat",
        "revision": "f7fcf8d02665cbcf07e97b2492b58be9"
    },
    {
        "url": "cache/frame_34.png",
        "revision": "72698abce1e633a798c1e4778f2f1b93"
    },
    {
        "url": "cache/frame_35.dat",
        "revision": "5b5ecdbf418448b208b402f73afcc1d7"
    },
    {
        "url": "cache/frame_35.png",
        "revision": "c87869bf4bf45da1c7127c6de2a0f11c"
    },
    {
        "url": "cache/frame_36.dat",
        "revision": "03912dc10e6c9548be0475a3d1a8bd36"
    },
    {
        "url": "cache/frame_36.png",
        "revision": "e5dd2ab9dcb0ebfcc208cab72482fd15"
    },
    {
        "url": "cache/frame_37.dat",
        "revision": "ac1584560973137f64a713b1cf135d95"
    },
    {
        "url": "cache/frame_37.png",
        "revision": "085b9a14931e24612d5a31d68dcb23ff"
    },
    {
        "url": "cache/frame_38.dat",
        "revision": "b45ceadcace8ab29ae23f1187827ee81"
    },
    {
        "url": "cache/frame_38.png",
        "revision": "a5b05f453ec538e590f8d89587a23611"
    },
    {
        "url": "cache/frame_39.dat",
        "revision": "1d62f529bdb36150d01a50edec41274b"
    },
    {
        "url": "cache/frame_39.png",
        "revision": "c83d4b2895ef4131002922efbab49a28"
    },
    {
        "url": "cache/frame_4.dat",
        "revision": "8f7cc1859eb9a53b5632292e3a130294"
    },
    {
        "url": "cache/frame_4.png",
        "revision": "b358fec2b171d3f48ed37760f2e43b4a"
    },
    {
        "url": "cache/frame_40.dat",
        "revision": "49e85960945738760a4657d66c955ec6"
    },
    {
        "url": "cache/frame_40.png",
        "revision": "4dbb42edd5532958d0a3373292ba907f"
    },
    {
        "url": "cache/frame_5.dat",
        "revision": "3163d7510e346dc920d4cb54a531c39d"
    },
    {
        "url": "cache/frame_5.png",
        "revision": "8fc575dc94ac96e59935a760eae530bc"
    },
    {
        "url": "cache/frame_6.dat",
        "revision": "8e295fa8a97640d442e0a0eb2071dbff"
    },
    {
        "url": "cache/frame_6.png",
        "revision": "e570a56ccb27e1123efa4f32875ebce0"
    },
    {
        "url": "cache/frame_7.dat",
        "revision": "daeda73b2271bc29305de751e93def4a"
    },
    {
        "url": "cache/frame_7.png",
        "revision": "f1f1f510346c6011a0a9db54a6ce1600"
    },
    {
        "url": "cache/frame_8.dat",
        "revision": "7fa3ac63497597e55d211749e725e1fb"
    },
    {
        "url": "cache/frame_8.png",
        "revision": "8da14e672ece3b8e6a87f6e730baf480"
    },
    {
        "url": "cache/frame_9.dat",
        "revision": "25c5097cb158d1871441f7c47dc39ee1"
    },
    {
        "url": "cache/frame_9.png",
        "revision": "e9c335a41a1ace41f43f096e488a4987"
    },
    {
        "url": "cache/mask_0/mask_101_0.dat",
        "revision": "6c4fdf704de27629d87b83d880801c64"
    },
    {
        "url": "cache/mask_0/mask_105_0.dat",
        "revision": "202eb068c963ec45eba3eb97d2870ce3"
    },
    {
        "url": "cache/mask_0/mask_109_0.dat",
        "revision": "d2a05381fcf529d73d253162ba809d74"
    },
    {
        "url": "cache/mask_0/mask_113_0.dat",
        "revision": "8a507f639e0b0556b6d92277cb5f392d"
    },
    {
        "url": "cache/mask_0/mask_117_0.dat",
        "revision": "a5a9ad0b479b2b21e5e20f313766f86f"
    },
    {
        "url": "cache/mask_0/mask_121_0.dat",
        "revision": "bccba8f234c62c4ab2f44ae44ab54cb9"
    },
    {
        "url": "cache/mask_0/mask_125_0.dat",
        "revision": "f4701c9eb001f32bacb2084bfa3e985a"
    },
    {
        "url": "cache/mask_0/mask_129_0.dat",
        "revision": "a1ebe9f05b055f64f558a6244e6c7890"
    },
    {
        "url": "cache/mask_0/mask_133_0.dat",
        "revision": "d2929cb58d6e9cd60e8a119be822d309"
    },
    {
        "url": "cache/mask_0/mask_137_0.dat",
        "revision": "dcd93d58f4072469967980ba59574f40"
    },
    {
        "url": "cache/mask_0/mask_141_0.dat",
        "revision": "5ffc654902a36e2b332fda9d59091fff"
    },
    {
        "url": "cache/mask_0/mask_145_0.dat",
        "revision": "9efe56fe464d4502494a1cf626fe9dec"
    },
    {
        "url": "cache/mask_0/mask_149_0.dat",
        "revision": "b4e966f8336481fe22747556591cd120"
    },
    {
        "url": "cache/mask_0/mask_153_0.dat",
        "revision": "f4e6a1e8b8d358caf45684afdff31294"
    },
    {
        "url": "cache/mask_0/mask_157_0.dat",
        "revision": "f6ffbde0114c9697566688b47a6711d6"
    },
    {
        "url": "cache/mask_0/mask_161_0.dat",
        "revision": "62f427d65bb9b4443d2e7ade8d459eb7"
    },
    {
        "url": "cache/mask_0/mask_165_0.dat",
        "revision": "0e55dfeac94cd03d80ac3beadf229be2"
    },
    {
        "url": "cache/mask_0/mask_169_0.dat",
        "revision": "e9d7cf1075155e841397c34439cb7727"
    },
    {
        "url": "cache/mask_0/mask_173_0.dat",
        "revision": "5e921e75199ac8624f0bda6b7c8a0ca5"
    },
    {
        "url": "cache/mask_0/mask_177_0.dat",
        "revision": "ddb00baf98441c85e41289c22725c176"
    },
    {
        "url": "cache/mask_0/mask_21_0.dat",
        "revision": "0718577fa2c550f18c1ada43073686c3"
    },
    {
        "url": "cache/mask_0/mask_25_0.dat",
        "revision": "86dff5e28a8686795053144e8e1a1468"
    },
    {
        "url": "cache/mask_0/mask_29_0.dat",
        "revision": "0e10a1d9372b0d19001975e9cfae0283"
    },
    {
        "url": "cache/mask_0/mask_33_0.dat",
        "revision": "f80d9b95cdc71d8569289bdf50461c0f"
    },
    {
        "url": "cache/mask_0/mask_37_0.dat",
        "revision": "a29b43128de8475414f71c138a48ff39"
    },
    {
        "url": "cache/mask_0/mask_41_0.dat",
        "revision": "994bd068e5e27de60ab2c80f741a3305"
    },
    {
        "url": "cache/mask_0/mask_45_0.dat",
        "revision": "081b0e72ce1c7c98b19a9569ac3a44dd"
    },
    {
        "url": "cache/mask_0/mask_49_0.dat",
        "revision": "f50d98727bbdb9f8550cc9170f2ec5f9"
    },
    {
        "url": "cache/mask_0/mask_53_0.dat",
        "revision": "4f116fa5476c96c493d9fa39144f3e0b"
    },
    {
        "url": "cache/mask_0/mask_57_0.dat",
        "revision": "63842c6c6382a6e9ad6ad9a5d260e10f"
    },
    {
        "url": "cache/mask_0/mask_61_0.dat",
        "revision": "a8c349ae832d6ecf6393bab781285d43"
    },
    {
        "url": "cache/mask_0/mask_65_0.dat",
        "revision": "e025e048393a0ef230ecfca730627d67"
    },
    {
        "url": "cache/mask_0/mask_69_0.dat",
        "revision": "03b969d8d5cc667b9db6d30435ed0465"
    },
    {
        "url": "cache/mask_0/mask_73_0.dat",
        "revision": "b4ddb6571dfa5e097778529e515aa991"
    },
    {
        "url": "cache/mask_0/mask_77_0.dat",
        "revision": "c958cba6bf9169ed0b5e5e812bde8407"
    },
    {
        "url": "cache/mask_0/mask_81_0.dat",
        "revision": "59352f5a91fdda1c299839c388b31094"
    },
    {
        "url": "cache/mask_0/mask_85_0.dat",
        "revision": "27d360595156bca380e0882db865d97f"
    },
    {
        "url": "cache/mask_0/mask_89_0.dat",
        "revision": "340efa3d23812287232ab47d46acc7f4"
    },
    {
        "url": "cache/mask_0/mask_93_0.dat",
        "revision": "071afbef25ba4ce443fe371d286d3f4b"
    },
    {
        "url": "cache/mask_0/mask_97_0.dat",
        "revision": "89b20fb88a32644757ee346306a23203"
    },
    {
        "url": "cache/mask_1/mask_101_1.dat",
        "revision": "bf6ab6978bd3e4ddece1c510e84e286d"
    },
    {
        "url": "cache/mask_1/mask_105_1.dat",
        "revision": "9d953276346ed743a173ea8ca0e8cd2b"
    },
    {
        "url": "cache/mask_1/mask_109_1.dat",
        "revision": "e0b18b6aae70d01b424bcf2f37f76f92"
    },
    {
        "url": "cache/mask_1/mask_113_1.dat",
        "revision": "ad0a4162bb87fc14323e8fc95da0f491"
    },
    {
        "url": "cache/mask_1/mask_117_1.dat",
        "revision": "cd26e07902b23b0c743505a2732b2498"
    },
    {
        "url": "cache/mask_1/mask_121_1.dat",
        "revision": "3755b5cde7076711cb29fbb86e8a0e7f"
    },
    {
        "url": "cache/mask_1/mask_125_1.dat",
        "revision": "ca310b53c8ec27d0718e3ef9211d723c"
    },
    {
        "url": "cache/mask_1/mask_129_1.dat",
        "revision": "56d78d56fd0bd490a806a9d0a418b93c"
    },
    {
        "url": "cache/mask_1/mask_133_1.dat",
        "revision": "25d97fb00854adb525107f41f3178204"
    },
    {
        "url": "cache/mask_1/mask_137_1.dat",
        "revision": "c46aabe94b0f98709e634f4722bdb5cf"
    },
    {
        "url": "cache/mask_1/mask_141_1.dat",
        "revision": "261a83e7dcf606694332c6c9e04b2b2e"
    },
    {
        "url": "cache/mask_1/mask_145_1.dat",
        "revision": "38d5d0690e4603854cc05d315f1dd9c5"
    },
    {
        "url": "cache/mask_1/mask_149_1.dat",
        "revision": "aa2eca119e10ec7b9b68a0114ac564ad"
    },
    {
        "url": "cache/mask_1/mask_153_1.dat",
        "revision": "7afe60df62eed29834a72c7a0fa036b1"
    },
    {
        "url": "cache/mask_1/mask_157_1.dat",
        "revision": "5d9825afa01b120972f1078079d94fd1"
    },
    {
        "url": "cache/mask_1/mask_161_1.dat",
        "revision": "226022ea7568c6713f7ced33d58cd0c3"
    },
    {
        "url": "cache/mask_1/mask_165_1.dat",
        "revision": "84ae6b587247749c38c4f95eb13db733"
    },
    {
        "url": "cache/mask_1/mask_169_1.dat",
        "revision": "7e6db5dc520265a7c2e1b5f840b1aac0"
    },
    {
        "url": "cache/mask_1/mask_173_1.dat",
        "revision": "3ce3d555e49b7cb1598b571cd9c39d11"
    },
    {
        "url": "cache/mask_1/mask_177_1.dat",
        "revision": "82e07b24b1381c1f679c9ee6dfadccf7"
    },
    {
        "url": "cache/mask_1/mask_21_1.dat",
        "revision": "bee4cdaef688947610b10b469c563994"
    },
    {
        "url": "cache/mask_1/mask_25_1.dat",
        "revision": "4290a56446ca90443215f2fb4c1959aa"
    },
    {
        "url": "cache/mask_1/mask_29_1.dat",
        "revision": "2456b09ddffa9f6c024d0146b2de747b"
    },
    {
        "url": "cache/mask_1/mask_33_1.dat",
        "revision": "9d41f80f181d65bb09c4fac192180588"
    },
    {
        "url": "cache/mask_1/mask_37_1.dat",
        "revision": "188e3cdd055dba53f9e428491adafe77"
    },
    {
        "url": "cache/mask_1/mask_41_1.dat",
        "revision": "0dd7fad119dc0f8d64027c8cb7b87b8d"
    },
    {
        "url": "cache/mask_1/mask_45_1.dat",
        "revision": "c0a3c6ed3d6c9e87235f3118c529e20d"
    },
    {
        "url": "cache/mask_1/mask_49_1.dat",
        "revision": "2d78d9b0d2ca5f8c2f70a0aee7c91c72"
    },
    {
        "url": "cache/mask_1/mask_53_1.dat",
        "revision": "5335af744066a31f48d6e3cab2b40dbe"
    },
    {
        "url": "cache/mask_1/mask_57_1.dat",
        "revision": "df0543a3e8403ccfbadc87e1f711c006"
    },
    {
        "url": "cache/mask_1/mask_61_1.dat",
        "revision": "87976040b3e1c0f0ef6ce09a100e8a6f"
    },
    {
        "url": "cache/mask_1/mask_65_1.dat",
        "revision": "63efa207af9229d00444dc5ffbd0554f"
    },
    {
        "url": "cache/mask_1/mask_69_1.dat",
        "revision": "aae34841ca735ca390f8542ee03afdf2"
    },
    {
        "url": "cache/mask_1/mask_73_1.dat",
        "revision": "8493bba42242fb0a464247675a7a35c1"
    },
    {
        "url": "cache/mask_1/mask_77_1.dat",
        "revision": "3e8c67e245d2d273cb14e773d6a9dfaa"
    },
    {
        "url": "cache/mask_1/mask_81_1.dat",
        "revision": "0340c9c4ccd8a3840523a734655afa3f"
    },
    {
        "url": "cache/mask_1/mask_85_1.dat",
        "revision": "b0743efcadd883a6597eca6c32cf1f66"
    },
    {
        "url": "cache/mask_1/mask_89_1.dat",
        "revision": "f68463319238c992e1672fb74874096e"
    },
    {
        "url": "cache/mask_1/mask_93_1.dat",
        "revision": "ea4adb79715c58e337a875b4e4a3956c"
    },
    {
        "url": "cache/mask_1/mask_97_1.dat",
        "revision": "e8c8a30ab35215bdd8dbf715ed1cda6a"
    },
    {
        "url": "cache/mask_2/mask_101_2.dat",
        "revision": "c19bd200710ef2a60c5758db76df1202"
    },
    {
        "url": "cache/mask_2/mask_105_2.dat",
        "revision": "1bf1c38f25b93af043bacc05798748ac"
    },
    {
        "url": "cache/mask_2/mask_109_2.dat",
        "revision": "bffead7278a51efb89b94e6d267f13f0"
    },
    {
        "url": "cache/mask_2/mask_113_2.dat",
        "revision": "84cbf90c73ba9a78c0a283b7e70c4ca6"
    },
    {
        "url": "cache/mask_2/mask_117_2.dat",
        "revision": "f9fa108e550908a5a1f1087b92bf2154"
    },
    {
        "url": "cache/mask_2/mask_121_2.dat",
        "revision": "0b6414fb6f76bfe0381c6cb2aacd34ba"
    },
    {
        "url": "cache/mask_2/mask_125_2.dat",
        "revision": "aca184e91ebb60548c7118e17c10de73"
    },
    {
        "url": "cache/mask_2/mask_129_2.dat",
        "revision": "0e929552e878974a3951d1eabb31a694"
    },
    {
        "url": "cache/mask_2/mask_133_2.dat",
        "revision": "2fe6a8bd3fbe0805d5247952d398d8e9"
    },
    {
        "url": "cache/mask_2/mask_137_2.dat",
        "revision": "563bfe8ba15383804f83ca96d39a8896"
    },
    {
        "url": "cache/mask_2/mask_141_2.dat",
        "revision": "0f554119e613553d0e290496578d827b"
    },
    {
        "url": "cache/mask_2/mask_145_2.dat",
        "revision": "ef3c2eae15e4726bb8803ad2c41dd635"
    },
    {
        "url": "cache/mask_2/mask_149_2.dat",
        "revision": "24353d418076add713c045cbd20570a6"
    },
    {
        "url": "cache/mask_2/mask_153_2.dat",
        "revision": "3d413b652cfe3d99374e30688053b90c"
    },
    {
        "url": "cache/mask_2/mask_157_2.dat",
        "revision": "6e1c88422eb13dd8489d464e3281ee82"
    },
    {
        "url": "cache/mask_2/mask_161_2.dat",
        "revision": "53b23561c00e1d00b8f575b3cac30ab8"
    },
    {
        "url": "cache/mask_2/mask_165_2.dat",
        "revision": "8e84496c645a09f23cd18bdbb725c31f"
    },
    {
        "url": "cache/mask_2/mask_169_2.dat",
        "revision": "990a5c2ece92d9d0e07228b7fbf898de"
    },
    {
        "url": "cache/mask_2/mask_173_2.dat",
        "revision": "9749985009d535e753d29ea300456be6"
    },
    {
        "url": "cache/mask_2/mask_177_2.dat",
        "revision": "c3c527e46e0dd6909193a06e30cc5f9a"
    },
    {
        "url": "cache/mask_2/mask_21_2.dat",
        "revision": "ef7fd6a1deb6cc2e393ace6dd84d5a36"
    },
    {
        "url": "cache/mask_2/mask_25_2.dat",
        "revision": "eabdf7cb85e1cf0bdb7952438a24e1cd"
    },
    {
        "url": "cache/mask_2/mask_29_2.dat",
        "revision": "e39952d54f008e8d39ad61172d7a6fcd"
    },
    {
        "url": "cache/mask_2/mask_33_2.dat",
        "revision": "ceb77e491c9ab253730ba4e72fd948ba"
    },
    {
        "url": "cache/mask_2/mask_37_2.dat",
        "revision": "85edba0353ded1e99ef4f7a962cbac1f"
    },
    {
        "url": "cache/mask_2/mask_41_2.dat",
        "revision": "7760ee0c6c86087fcde96e2eae9cb90d"
    },
    {
        "url": "cache/mask_2/mask_45_2.dat",
        "revision": "3e38a0052f6badc68191d3ee3069e3d9"
    },
    {
        "url": "cache/mask_2/mask_49_2.dat",
        "revision": "47ca1f72a8d43d06211b16cc98349abd"
    },
    {
        "url": "cache/mask_2/mask_53_2.dat",
        "revision": "419e2b85764065370e791d4602b3d6cd"
    },
    {
        "url": "cache/mask_2/mask_57_2.dat",
        "revision": "3c1fa898079586f5338aff22ad3e5e1c"
    },
    {
        "url": "cache/mask_2/mask_61_2.dat",
        "revision": "d6e4a7bd67c891d213e2f4e79188fa87"
    },
    {
        "url": "cache/mask_2/mask_65_2.dat",
        "revision": "6eddee56c23be857e881eed534e36bc3"
    },
    {
        "url": "cache/mask_2/mask_69_2.dat",
        "revision": "e68f0f694c8c9a5f3f86a2906cdbe67a"
    },
    {
        "url": "cache/mask_2/mask_73_2.dat",
        "revision": "54c839fcf1bf0a5251ea3d6458f75623"
    },
    {
        "url": "cache/mask_2/mask_77_2.dat",
        "revision": "622903170480ae4ba0a41549544cf47b"
    },
    {
        "url": "cache/mask_2/mask_81_2.dat",
        "revision": "3c55f79ff8ea70dd8a0862f351b2f3d0"
    },
    {
        "url": "cache/mask_2/mask_85_2.dat",
        "revision": "3adfad79aca1860f53b719d3d6d48190"
    },
    {
        "url": "cache/mask_2/mask_89_2.dat",
        "revision": "272d60997a9a1691cbe3091733e29162"
    },
    {
        "url": "cache/mask_2/mask_93_2.dat",
        "revision": "f17848e3c1aa7981607d62355e36f2d5"
    },
    {
        "url": "cache/mask_2/mask_97_2.dat",
        "revision": "85effa425682735086394a0c7bbafbb0"
    },
    {
        "url": "cache/mask_3/mask_101_3.dat",
        "revision": "ae198375944bf5e5db80ed22e67b68b6"
    },
    {
        "url": "cache/mask_3/mask_105_3.dat",
        "revision": "6015c6e5f50aa989e01dd58097533ac3"
    },
    {
        "url": "cache/mask_3/mask_109_3.dat",
        "revision": "0aff2d331afacd144a9358b0d74facc0"
    },
    {
        "url": "cache/mask_3/mask_113_3.dat",
        "revision": "8f19e9effc6dd1c0fc6479bd67c48bf9"
    },
    {
        "url": "cache/mask_3/mask_117_3.dat",
        "revision": "a2b2164b64aa246005688ff289cf1a4e"
    },
    {
        "url": "cache/mask_3/mask_121_3.dat",
        "revision": "5c2f2642b172d9fe4b65fff2f1dadd62"
    },
    {
        "url": "cache/mask_3/mask_125_3.dat",
        "revision": "9f3ad8403cb0e4dee43b6d1120704c42"
    },
    {
        "url": "cache/mask_3/mask_129_3.dat",
        "revision": "b2849c22daa0217d68aa604856b9a78d"
    },
    {
        "url": "cache/mask_3/mask_133_3.dat",
        "revision": "e81d804c6c49187029b6570262984b81"
    },
    {
        "url": "cache/mask_3/mask_137_3.dat",
        "revision": "a59f1c0e5ad80120c501911dc9ef2145"
    },
    {
        "url": "cache/mask_3/mask_141_3.dat",
        "revision": "037a2695936927ee7a1707b4811124b7"
    },
    {
        "url": "cache/mask_3/mask_145_3.dat",
        "revision": "be939feee94f6d6d6ccc81ae1f600dbd"
    },
    {
        "url": "cache/mask_3/mask_149_3.dat",
        "revision": "3196a80f19d3569d2f46ca1c30b8a24b"
    },
    {
        "url": "cache/mask_3/mask_153_3.dat",
        "revision": "546b11d703368abb4c0d32a8d9c37982"
    },
    {
        "url": "cache/mask_3/mask_157_3.dat",
        "revision": "8470a13e8aacd293d2553bdd313c0f3d"
    },
    {
        "url": "cache/mask_3/mask_161_3.dat",
        "revision": "d094c5c953718c9f00cffb2e0d71c2f6"
    },
    {
        "url": "cache/mask_3/mask_165_3.dat",
        "revision": "aa34451d98a131743df4bb1d5fd260f1"
    },
    {
        "url": "cache/mask_3/mask_169_3.dat",
        "revision": "08548e5d2e1bdad75f9ed1b97b6c8152"
    },
    {
        "url": "cache/mask_3/mask_173_3.dat",
        "revision": "7e7cb6489490d6e668a85b812b0b2612"
    },
    {
        "url": "cache/mask_3/mask_177_3.dat",
        "revision": "7f21c6fbc48b877e5b31caac71633886"
    },
    {
        "url": "cache/mask_3/mask_21_3.dat",
        "revision": "986c775b20f9bc975c3a83faee76329c"
    },
    {
        "url": "cache/mask_3/mask_25_3.dat",
        "revision": "d62b82857c88be6ef18f4afb4cf09d56"
    },
    {
        "url": "cache/mask_3/mask_29_3.dat",
        "revision": "9f8058257aa8b76d8445b9bb22b9c05a"
    },
    {
        "url": "cache/mask_3/mask_33_3.dat",
        "revision": "4f1e8177a0c749ac3931d81c983ffa40"
    },
    {
        "url": "cache/mask_3/mask_37_3.dat",
        "revision": "88c26716f6735be2fb4131eed5058051"
    },
    {
        "url": "cache/mask_3/mask_41_3.dat",
        "revision": "7d652cb4b36012bc9ba5a7e1d035159c"
    },
    {
        "url": "cache/mask_3/mask_45_3.dat",
        "revision": "3714071caccd1e070a2346b919d5f37b"
    },
    {
        "url": "cache/mask_3/mask_49_3.dat",
        "revision": "2e2242a88660982e6667bb7ef0fea8de"
    },
    {
        "url": "cache/mask_3/mask_53_3.dat",
        "revision": "87169242d83d8a40022bc9d4060798ae"
    },
    {
        "url": "cache/mask_3/mask_57_3.dat",
        "revision": "7c6f98cf3629b427436375da98857ac5"
    },
    {
        "url": "cache/mask_3/mask_61_3.dat",
        "revision": "6d1b20de6f2805cf18ef98970a7498ee"
    },
    {
        "url": "cache/mask_3/mask_65_3.dat",
        "revision": "e0e64afa29e61db165dfc2638cacea41"
    },
    {
        "url": "cache/mask_3/mask_69_3.dat",
        "revision": "68e564748c41b81d08e1a34a78a68296"
    },
    {
        "url": "cache/mask_3/mask_73_3.dat",
        "revision": "449a36d7abd76c05e25444c8a1d7db82"
    },
    {
        "url": "cache/mask_3/mask_77_3.dat",
        "revision": "446c00259878f35d8b468e640ad2ae51"
    },
    {
        "url": "cache/mask_3/mask_81_3.dat",
        "revision": "5e55ada7d9fc5f5237e7ef505ba703de"
    },
    {
        "url": "cache/mask_3/mask_85_3.dat",
        "revision": "b46ebcdc0121b1a3bedbd184495cfb88"
    },
    {
        "url": "cache/mask_3/mask_89_3.dat",
        "revision": "14f648b97ed382c545c8632ac4e1b6f5"
    },
    {
        "url": "cache/mask_3/mask_93_3.dat",
        "revision": "b2705428db6f3df45f0bf54bf7f7ebcf"
    },
    {
        "url": "cache/mask_3/mask_97_3.dat",
        "revision": "b0103bf0ceaa6d15e13c1ddf314837c7"
    },
    {
        "url": "cache/mask_4/mask_101_4.dat",
        "revision": "ca45a07682fbb6bc77a32e9a15314494"
    },
    {
        "url": "cache/mask_4/mask_105_4.dat",
        "revision": "7b74b40294afa78a889105b236e5a3cf"
    },
    {
        "url": "cache/mask_4/mask_109_4.dat",
        "revision": "2f88c8ed36981f3080a6f1e035173635"
    },
    {
        "url": "cache/mask_4/mask_113_4.dat",
        "revision": "d9a50ab9759fe8a037f4157e478d49ec"
    },
    {
        "url": "cache/mask_4/mask_117_4.dat",
        "revision": "df85ef67e5c4cf3267aedc9055ff9a2b"
    },
    {
        "url": "cache/mask_4/mask_121_4.dat",
        "revision": "7a66881619731b961dcfac808e2f6be0"
    },
    {
        "url": "cache/mask_4/mask_125_4.dat",
        "revision": "409a1bcff906697dfa1f4a2b83aa7f72"
    },
    {
        "url": "cache/mask_4/mask_129_4.dat",
        "revision": "c43f5c311576c0ce3537fcdc0aa9baaf"
    },
    {
        "url": "cache/mask_4/mask_133_4.dat",
        "revision": "1b0d84cfdbd3520dae9cea6779e6102e"
    },
    {
        "url": "cache/mask_4/mask_137_4.dat",
        "revision": "afad876a701bc44207b76b159cc624c4"
    },
    {
        "url": "cache/mask_4/mask_141_4.dat",
        "revision": "ff707a8bfc3a08df2715dace4eeee2c9"
    },
    {
        "url": "cache/mask_4/mask_145_4.dat",
        "revision": "e08158360699d664f225befb46faafae"
    },
    {
        "url": "cache/mask_4/mask_149_4.dat",
        "revision": "16b0984a56f48cb56afb82acd67671a8"
    },
    {
        "url": "cache/mask_4/mask_153_4.dat",
        "revision": "730cc2b3e3e12832a3d135dccec1985b"
    },
    {
        "url": "cache/mask_4/mask_157_4.dat",
        "revision": "9c80740894d87ac138659dd817cfd326"
    },
    {
        "url": "cache/mask_4/mask_161_4.dat",
        "revision": "4e5210091ec433c5c527d1f0585f73f7"
    },
    {
        "url": "cache/mask_4/mask_165_4.dat",
        "revision": "a6dbdfb0999db134cca08f7e30cfa7de"
    },
    {
        "url": "cache/mask_4/mask_169_4.dat",
        "revision": "9089622362230a309a438d6b3b552c1c"
    },
    {
        "url": "cache/mask_4/mask_173_4.dat",
        "revision": "56ea5b38d276af919f2c6544c9ca0c69"
    },
    {
        "url": "cache/mask_4/mask_177_4.dat",
        "revision": "87e64a44a0adf6eaeaff9dd68e771ad1"
    },
    {
        "url": "cache/mask_4/mask_21_4.dat",
        "revision": "c1328902261a4b750bffd6a322a69e43"
    },
    {
        "url": "cache/mask_4/mask_25_4.dat",
        "revision": "128cdfcfa192fb806a5d81f91ebc05dd"
    },
    {
        "url": "cache/mask_4/mask_29_4.dat",
        "revision": "1afb863e3bd5f551724cd5e0eaaa659f"
    },
    {
        "url": "cache/mask_4/mask_33_4.dat",
        "revision": "b60bbea04379a5edd6765ce656ec235f"
    },
    {
        "url": "cache/mask_4/mask_37_4.dat",
        "revision": "fdb59b9945c57ac798ce7f56b436d061"
    },
    {
        "url": "cache/mask_4/mask_41_4.dat",
        "revision": "6086f8d8e5e07367d4639ae9cb0ed432"
    },
    {
        "url": "cache/mask_4/mask_45_4.dat",
        "revision": "7c39a588c3a02a9f2df71bbb451185f6"
    },
    {
        "url": "cache/mask_4/mask_49_4.dat",
        "revision": "be9fe9f94ae480bec52518c31e252259"
    },
    {
        "url": "cache/mask_4/mask_53_4.dat",
        "revision": "db6c8031329065e5bcb48d6dc0f53d53"
    },
    {
        "url": "cache/mask_4/mask_57_4.dat",
        "revision": "b9d06f6aa6b2398637f04933cdbcd517"
    },
    {
        "url": "cache/mask_4/mask_61_4.dat",
        "revision": "f7bb6ffa6ccabbc9fa44aaceb8d50561"
    },
    {
        "url": "cache/mask_4/mask_65_4.dat",
        "revision": "04603c3e8d97ef14e2dad753e6eb93c3"
    },
    {
        "url": "cache/mask_4/mask_69_4.dat",
        "revision": "36df758133b3febd68156ab37d01a511"
    },
    {
        "url": "cache/mask_4/mask_73_4.dat",
        "revision": "51dd4eb76dff0927be98beedf05eaba7"
    },
    {
        "url": "cache/mask_4/mask_77_4.dat",
        "revision": "dd103faf186586280ffe0641e2b7978f"
    },
    {
        "url": "cache/mask_4/mask_81_4.dat",
        "revision": "90a9312e91e290c7391df673683fd487"
    },
    {
        "url": "cache/mask_4/mask_85_4.dat",
        "revision": "d8216a889322d1935a3e7d26fefa473d"
    },
    {
        "url": "cache/mask_4/mask_89_4.dat",
        "revision": "6396c3787c999f1d409da28ec4e0e7ee"
    },
    {
        "url": "cache/mask_4/mask_93_4.dat",
        "revision": "e9d3369fdd1d79792395646f5923e1fc"
    },
    {
        "url": "cache/mask_4/mask_97_4.dat",
        "revision": "77535b91df7f053f8931260141afe6b7"
    },
    {
        "url": "cache/mask_5/mask_101_5.dat",
        "revision": "63e4303918909723ece25197688b8ba7"
    },
    {
        "url": "cache/mask_5/mask_105_5.dat",
        "revision": "ee01fae3b22b508e1adb3f47dc99c941"
    },
    {
        "url": "cache/mask_5/mask_109_5.dat",
        "revision": "1325823b4e7600739d46c64d4212a5d1"
    },
    {
        "url": "cache/mask_5/mask_113_5.dat",
        "revision": "c01d8795c46106917095511b9930c0a0"
    },
    {
        "url": "cache/mask_5/mask_117_5.dat",
        "revision": "fbd2cd3349eb860d77369d4b0b944537"
    },
    {
        "url": "cache/mask_5/mask_121_5.dat",
        "revision": "156bb97e4e652111cc8969c8c2c15e8e"
    },
    {
        "url": "cache/mask_5/mask_125_5.dat",
        "revision": "0cb7294228c178cdd823b6a644967f1e"
    },
    {
        "url": "cache/mask_5/mask_129_5.dat",
        "revision": "05635b96e33640886e90b4b8d56171a4"
    },
    {
        "url": "cache/mask_5/mask_133_5.dat",
        "revision": "afb77cc82a0b754c7e8c896484430fdd"
    },
    {
        "url": "cache/mask_5/mask_137_5.dat",
        "revision": "5dd206b6f8cef84943004dd46473e209"
    },
    {
        "url": "cache/mask_5/mask_141_5.dat",
        "revision": "de316b74fdb13d4e2dd231db258e5b10"
    },
    {
        "url": "cache/mask_5/mask_145_5.dat",
        "revision": "9db1a1f7ff00930a3a942ce19e5229f8"
    },
    {
        "url": "cache/mask_5/mask_149_5.dat",
        "revision": "616f4baac1ccb75cebae890ca66cc639"
    },
    {
        "url": "cache/mask_5/mask_153_5.dat",
        "revision": "6a244fbd16d99c00d881e7229626d838"
    },
    {
        "url": "cache/mask_5/mask_157_5.dat",
        "revision": "fe12067a1b756e60b55402cd8ecd24d6"
    },
    {
        "url": "cache/mask_5/mask_161_5.dat",
        "revision": "6447ad594af51dcfa9f972e82a21e54e"
    },
    {
        "url": "cache/mask_5/mask_165_5.dat",
        "revision": "9301e05832397fd35cda0704d5a64e85"
    },
    {
        "url": "cache/mask_5/mask_169_5.dat",
        "revision": "7ce18389a7d8a4eddd78e837665fa379"
    },
    {
        "url": "cache/mask_5/mask_173_5.dat",
        "revision": "3e39ad33f5a469258e348dd7dbb83b1e"
    },
    {
        "url": "cache/mask_5/mask_177_5.dat",
        "revision": "a5a8a619dba0f1ff547e228fc05696aa"
    },
    {
        "url": "cache/mask_5/mask_21_5.dat",
        "revision": "7ea675316e14102a14ae2cc70897fd7f"
    },
    {
        "url": "cache/mask_5/mask_25_5.dat",
        "revision": "d850e1d1e779dae8073761378b6ce671"
    },
    {
        "url": "cache/mask_5/mask_29_5.dat",
        "revision": "150bfabd079b92aa70ab30a7e9368dfe"
    },
    {
        "url": "cache/mask_5/mask_33_5.dat",
        "revision": "213369f74b18f08edea17c351d141103"
    },
    {
        "url": "cache/mask_5/mask_37_5.dat",
        "revision": "b41c0f5323c4fa71a305521ba452b09d"
    },
    {
        "url": "cache/mask_5/mask_41_5.dat",
        "revision": "6dea7e67b63ea326f85517d1c4c56d69"
    },
    {
        "url": "cache/mask_5/mask_45_5.dat",
        "revision": "829091dac90854289ec9bcf351774a9d"
    },
    {
        "url": "cache/mask_5/mask_49_5.dat",
        "revision": "9c3e06caa2d4917b7b5450ce0a27a7cf"
    },
    {
        "url": "cache/mask_5/mask_53_5.dat",
        "revision": "4a81ede5d9554feb48b079e76a895fd1"
    },
    {
        "url": "cache/mask_5/mask_57_5.dat",
        "revision": "5194ce0c45d7d9676abaf2fa2cef99fc"
    },
    {
        "url": "cache/mask_5/mask_61_5.dat",
        "revision": "863bf39b5bcda2ad4767fb9027770695"
    },
    {
        "url": "cache/mask_5/mask_65_5.dat",
        "revision": "9c7fc509da9e5df7e5edbc2a1ae55fd0"
    },
    {
        "url": "cache/mask_5/mask_69_5.dat",
        "revision": "1d9d0d5c8c2c9d3e1f47e43d7a4d0869"
    },
    {
        "url": "cache/mask_5/mask_73_5.dat",
        "revision": "21200ef88b501d6d22dfe931100fd4c8"
    },
    {
        "url": "cache/mask_5/mask_77_5.dat",
        "revision": "517ed455f5eec7593ea201a2ed4cee5f"
    },
    {
        "url": "cache/mask_5/mask_81_5.dat",
        "revision": "b3e6de4ae3f3ee7c22e9731e8f951c97"
    },
    {
        "url": "cache/mask_5/mask_85_5.dat",
        "revision": "cbe89ebc95a4c3a1ef3eeb9cb81f89e2"
    },
    {
        "url": "cache/mask_5/mask_89_5.dat",
        "revision": "8c2bc4a7da237a03224e2301d3895e33"
    },
    {
        "url": "cache/mask_5/mask_93_5.dat",
        "revision": "513cb1d0cab1c36d1eca4484340c5e66"
    },
    {
        "url": "cache/mask_5/mask_97_5.dat",
        "revision": "c9940067833f5e8e6a29eeb04f99a705"
    },
    {
        "url": "cache/mask_6/mask_101_6.dat",
        "revision": "fe3409bab63a28fd156562843368940b"
    },
    {
        "url": "cache/mask_6/mask_105_6.dat",
        "revision": "34efa23c98039ef903960e7fa0592653"
    },
    {
        "url": "cache/mask_6/mask_109_6.dat",
        "revision": "36ea76ef2e46af972407d49ff8da9387"
    },
    {
        "url": "cache/mask_6/mask_113_6.dat",
        "revision": "03c97aec73f929287857fe364305c984"
    },
    {
        "url": "cache/mask_6/mask_117_6.dat",
        "revision": "a9db9006460b267fdd008ee6d7961930"
    },
    {
        "url": "cache/mask_6/mask_121_6.dat",
        "revision": "c252620b89e84448b2503203387b4cb9"
    },
    {
        "url": "cache/mask_6/mask_125_6.dat",
        "revision": "b2163f500e8c2dc3e14442bbcf1ae2d4"
    },
    {
        "url": "cache/mask_6/mask_129_6.dat",
        "revision": "0aecf6a2b535e1036bd64c688b65191e"
    },
    {
        "url": "cache/mask_6/mask_133_6.dat",
        "revision": "fe8e9a6d458264eb66ad124528bc47cb"
    },
    {
        "url": "cache/mask_6/mask_137_6.dat",
        "revision": "09421a3a805e387e6250cb1c87afcb5b"
    },
    {
        "url": "cache/mask_6/mask_141_6.dat",
        "revision": "9910802e214f42ae2abdcee85116c2e3"
    },
    {
        "url": "cache/mask_6/mask_145_6.dat",
        "revision": "aef30014661d9963c9617938bda7e2d3"
    },
    {
        "url": "cache/mask_6/mask_149_6.dat",
        "revision": "2f9da67a9504c0deca5121d321b200e8"
    },
    {
        "url": "cache/mask_6/mask_153_6.dat",
        "revision": "3c6c97c86dc381a338e67917478f3855"
    },
    {
        "url": "cache/mask_6/mask_157_6.dat",
        "revision": "51b4b3cf7dddb9debe256fd8911a05f6"
    },
    {
        "url": "cache/mask_6/mask_161_6.dat",
        "revision": "e3f360c52072bbfa68ef4d7f68c1970b"
    },
    {
        "url": "cache/mask_6/mask_165_6.dat",
        "revision": "b5a9a0a0b8a48e2e193f941535c6484b"
    },
    {
        "url": "cache/mask_6/mask_169_6.dat",
        "revision": "2b32a6d292ed03b746cd73f8f5d59f02"
    },
    {
        "url": "cache/mask_6/mask_173_6.dat",
        "revision": "54f997312cdc4ef751491cfaf3308c66"
    },
    {
        "url": "cache/mask_6/mask_177_6.dat",
        "revision": "92cacc6329349c5effbddeb9a2e559fa"
    },
    {
        "url": "cache/mask_6/mask_21_6.dat",
        "revision": "1e2c0fc394840848946b2879a8ea0e58"
    },
    {
        "url": "cache/mask_6/mask_25_6.dat",
        "revision": "67ededb602cd3eea65bd7cd15b3b8aba"
    },
    {
        "url": "cache/mask_6/mask_29_6.dat",
        "revision": "ae9e79b8d717906f2cee4ac758ed5768"
    },
    {
        "url": "cache/mask_6/mask_33_6.dat",
        "revision": "ca09e953f305a38d9e82b1a566c6c856"
    },
    {
        "url": "cache/mask_6/mask_37_6.dat",
        "revision": "f1174b18aeeacd12b2efe0d1d9316c99"
    },
    {
        "url": "cache/mask_6/mask_41_6.dat",
        "revision": "eb25abab0eccbe9b50e0727f65ddfb3e"
    },
    {
        "url": "cache/mask_6/mask_45_6.dat",
        "revision": "e9df8dc1d0d56c4187a0081323998076"
    },
    {
        "url": "cache/mask_6/mask_49_6.dat",
        "revision": "3fe09ab83277240614e315932f768afa"
    },
    {
        "url": "cache/mask_6/mask_53_6.dat",
        "revision": "83c85d40e678c9b37c2d37f401bc14ee"
    },
    {
        "url": "cache/mask_6/mask_57_6.dat",
        "revision": "4e807ebe4413aa11b14af7a0a9d42a50"
    },
    {
        "url": "cache/mask_6/mask_61_6.dat",
        "revision": "10b367e0da3f5d0b5fe0b91e830f5653"
    },
    {
        "url": "cache/mask_6/mask_65_6.dat",
        "revision": "c0b3bba3387d20f796672ffe9d0e38f9"
    },
    {
        "url": "cache/mask_6/mask_69_6.dat",
        "revision": "a37fef158283319557bd0bf3ebe4846d"
    },
    {
        "url": "cache/mask_6/mask_73_6.dat",
        "revision": "d9b39a4a9a1a7da544faba4a74c23d04"
    },
    {
        "url": "cache/mask_6/mask_77_6.dat",
        "revision": "3268bdbf71bfcd6eca66a6e3dbed48b9"
    },
    {
        "url": "cache/mask_6/mask_81_6.dat",
        "revision": "74955ed39c6185272affaeb81090919b"
    },
    {
        "url": "cache/mask_6/mask_85_6.dat",
        "revision": "26e0c67dd75a268b3efc628d38d932da"
    },
    {
        "url": "cache/mask_6/mask_89_6.dat",
        "revision": "a37653e6a06e2c536a8f585a005ef7f0"
    },
    {
        "url": "cache/mask_6/mask_93_6.dat",
        "revision": "3ac10716db6cdd2859a807b9f95a18a2"
    },
    {
        "url": "cache/mask_6/mask_97_6.dat",
        "revision": "7d9e1ddc9553878f2931db40fc6ed0e0"
    },
    {
        "url": "cache/mask_7/mask_101_7.dat",
        "revision": "e83d50dcfeddecf35f5bed16b54bbba8"
    },
    {
        "url": "cache/mask_7/mask_105_7.dat",
        "revision": "e3bb1535f7075601e2cbb165173421f4"
    },
    {
        "url": "cache/mask_7/mask_109_7.dat",
        "revision": "fe7590ee146b69ad00b7169c08a6ab58"
    },
    {
        "url": "cache/mask_7/mask_113_7.dat",
        "revision": "84b1badf25a7a5cc4407b2174404821e"
    },
    {
        "url": "cache/mask_7/mask_117_7.dat",
        "revision": "4e4233f2b6a3e9b1fa28e68ed52b037f"
    },
    {
        "url": "cache/mask_7/mask_121_7.dat",
        "revision": "c9996c9461742edfab6dda88b613585a"
    },
    {
        "url": "cache/mask_7/mask_125_7.dat",
        "revision": "f4553613c89cf07e4561ad2aae92e0cc"
    },
    {
        "url": "cache/mask_7/mask_129_7.dat",
        "revision": "b4edc59c5e1f790379f71351f196e6bc"
    },
    {
        "url": "cache/mask_7/mask_133_7.dat",
        "revision": "e6a4f6fa0a88402cdc0255ca95f5d199"
    },
    {
        "url": "cache/mask_7/mask_137_7.dat",
        "revision": "fd33075985f60259af6b7dfd2ae189e5"
    },
    {
        "url": "cache/mask_7/mask_141_7.dat",
        "revision": "ec73544083abf6bad1669d781bf09437"
    },
    {
        "url": "cache/mask_7/mask_145_7.dat",
        "revision": "75a6237d00e616ca916d977602c0cb7a"
    },
    {
        "url": "cache/mask_7/mask_149_7.dat",
        "revision": "a2d5667629afc9ea067e1839eacc8f68"
    },
    {
        "url": "cache/mask_7/mask_153_7.dat",
        "revision": "a01eb9a63c1920b705ff4d8b717f4ce7"
    },
    {
        "url": "cache/mask_7/mask_157_7.dat",
        "revision": "fad2e537867b26a49f29d60265c0fb40"
    },
    {
        "url": "cache/mask_7/mask_161_7.dat",
        "revision": "5d88f58b291f5bb88a0406cfa29012c8"
    },
    {
        "url": "cache/mask_7/mask_165_7.dat",
        "revision": "41a900ae9693e5c27d980fdbbd1cc439"
    },
    {
        "url": "cache/mask_7/mask_169_7.dat",
        "revision": "365708854b5a146db2b5580225d8048f"
    },
    {
        "url": "cache/mask_7/mask_173_7.dat",
        "revision": "13683d9f282668ed475bf707ee53e201"
    },
    {
        "url": "cache/mask_7/mask_177_7.dat",
        "revision": "8149d01010cee85d1849a9dca0e102a5"
    },
    {
        "url": "cache/mask_7/mask_21_7.dat",
        "revision": "7c80f76fd015f19e48b7a570d55bc262"
    },
    {
        "url": "cache/mask_7/mask_25_7.dat",
        "revision": "ea54a40e79f32877e02d1ea8791cb471"
    },
    {
        "url": "cache/mask_7/mask_29_7.dat",
        "revision": "a6f4995de8e329204ee3410b22d8da4d"
    },
    {
        "url": "cache/mask_7/mask_33_7.dat",
        "revision": "51273577e33506f83d00d7971fc38dc8"
    },
    {
        "url": "cache/mask_7/mask_37_7.dat",
        "revision": "8c0fbb3e5121299816be076ce6a356c4"
    },
    {
        "url": "cache/mask_7/mask_41_7.dat",
        "revision": "b97a30c39540b5160c652b5324ae9a08"
    },
    {
        "url": "cache/mask_7/mask_45_7.dat",
        "revision": "18166274b73ca16a2c5a145076b990dc"
    },
    {
        "url": "cache/mask_7/mask_49_7.dat",
        "revision": "270bfbf77a14569a5fc88925beb39189"
    },
    {
        "url": "cache/mask_7/mask_53_7.dat",
        "revision": "84e0be977afc54746e41e28f47de1ad9"
    },
    {
        "url": "cache/mask_7/mask_57_7.dat",
        "revision": "a37a26bece7e816a87ccdfcef7e96b71"
    },
    {
        "url": "cache/mask_7/mask_61_7.dat",
        "revision": "a108bbc684fb0ad8f59228f410d4124d"
    },
    {
        "url": "cache/mask_7/mask_65_7.dat",
        "revision": "647767fd83beeec449ef18e04ae12af7"
    },
    {
        "url": "cache/mask_7/mask_69_7.dat",
        "revision": "577baae8a8809899b6763719cf5bfa8d"
    },
    {
        "url": "cache/mask_7/mask_73_7.dat",
        "revision": "b2bf60ae1da1ce4bb7db15129e99d58b"
    },
    {
        "url": "cache/mask_7/mask_77_7.dat",
        "revision": "ab9a75a46a851ad80f0e57b6dd5c64da"
    },
    {
        "url": "cache/mask_7/mask_81_7.dat",
        "revision": "fcfaf88379459ac068236827681d9e43"
    },
    {
        "url": "cache/mask_7/mask_85_7.dat",
        "revision": "525c8b876f509a127d3dfd80d81aad3f"
    },
    {
        "url": "cache/mask_7/mask_89_7.dat",
        "revision": "7c7a821cb5e7d65e7b6e020bd6351f35"
    },
    {
        "url": "cache/mask_7/mask_93_7.dat",
        "revision": "c906b28ae62d8866a0eb35ae87db567f"
    },
    {
        "url": "cache/mask_7/mask_97_7.dat",
        "revision": "c04cea679212bda3930b3534565a6fd2"
    },
    {
        "url": "tools/merge.bat",
        "revision": "86e934a4304536ad09b2f7b9e814241d"
    },
    {
        "url": "tools/merge.php",
        "revision": "0b113c70589ac6cc76291087b3f3dff9"
    },
    {
        "url": "tools/merge.sh",
        "revision": "d2b77c3493b2ffe3d76d4fb9330e72a1"
    },
    {
        "url": "tools/merged_config.php",
        "revision": "8c4be9477ea9c372b3d2796df9d9d867"
    },
    {
        "url": "tools/merged_header.php",
        "revision": "3fc51eef6239691f523be743fde28470"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}